In [1]:
# Định Nghĩa :
#     K - Nearest Neighbor là một thuật toán supervised-learning đơn giản nhất 
#     K-NN được sử dụng để giải quyết cả 2 bài toán của Supervised Learning là Classficiation và Regression 
#     K-NN là một dạng Instance-base learning ( Memory base learning) Ở đây giải thích rằng độ phực tạp của 
#     Nó sẽ tăng theo dữ liệu ** cái này để sau khi tìm hiểu kỹ thì viết 
#     K-NN được coi là một thuật toán lười , được xếp vào loại LAZY LEARNING . 
#     Lý do là mọi tính toán được thực hiện khi nó cần dự đoán đưa ra kết quả mới 
# Cách hoạt động : 
#     K-NN là thuât toán tìm đầu ra dữ liệu mới bằng cách dựa trên thông tin của K phần tử gần nhất với nó 
#     Không quan tâm đến việc có một vài điểm dữ liệu gần nhất này là nhiễu 
    
#     Trong Hệ gợi ý phim ảnh với lõi của phuơng pháp lọc cộng tác sử dụng K-NN này có nghĩa là : 
#     Hiểu đơn giản : Chúng ta sẽ tính toán để xác định độ tương đương giữa các ( User-User) hoặc (Movide, Movie)
#     Từ đó đưa ra quyết định phim này có được yêu thích không bằng việc tính toán với K User gần nhất , hoặc 
#     K movie gần nhất 

In [2]:
# Về mặt tính toán :
    # Việc để xác định để lựa chọn được K phần tử có khoảng cách gần nhau . Ta cần xem xét Chuẩn Norn 
    # Thường dùng là chuẩn Norn 2
    

In [3]:
# Lợi Ích và Hạn Chế 


In [4]:
# Dữ Liệu :
    # Bộ dữ liệu này ta có thông tin của 3 loài Hoa Lan Iris setosa, Iris virginica và Iris versicolor...
    # Mỗi loại có 50 bông được đo với thông tin chiều dài , chiều rộng của đài hoa, chiều dài, chiều rộng cánh hoa
    # Ở đây dữ liệu được lưu với tên là iris , nó có sẵn trong thư viện scikit-learn

In [25]:
# CODE 
# LOAD DATA , PRINT SAMPLE DATA 
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets

iris = datasets.load_iris()
iris_X = iris.data # thong tin cua vector voi 4 chi so
iris_y = iris.target # Phan loai loai hoa tuong ung chay tu 1-3
print('Number of classes:', len(np.unique(iris_y)))
print('Number of data points:', len(iris_y))

#print(iris)

X0 = iris_X[iris_y ==0] # Tong hop cac bong hoa thuoc class 0
print('Sample data from class 0:\n', X0[:10,:])
X1 = iris_X[iris_y==1]
print('Sample data  from class 1:\n', X1[:10,:])
X2 = iris_X[iris_y==2]
print('Sample data  from class 2:\n', X2[:10,:])

Number of classes: 3
Number of data points: 150
Sample data from class 0:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
Sample data  from class 1:
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]]
Sample data  from class 2:
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]]


In [26]:
# CODE
# SPLIT TRAINING DATA, TEST DATA
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(iris_X, iris_y, test_size=50)
# X: data
# Y : Target
print('Training size: ', len(Y_train))
print('Test size: ', len(Y_test))


Training size:  100
Test size:  50


In [27]:
# CODE
# TRAIN WITH K =2
Clf = neighbors.KNeighborsClassifier(n_neighbors=2, p=2) # p =2 , Norn 2 
Clf.fit(X_train, Y_train)
Y_pred = Clf.predict(X_test)

print('Print results for 10 test data points:')
print("Predicted labels: \n", Y_pred[:10]) # predict target
print("Ground truth    : \n", Y_test[:10]) #real target 

Print results for 10 test data points:
Predicted labels: 
 [1 1 2 0 1 2 1 1 2 1]
Ground truth    : 
 [1 1 2 0 1 2 1 2 2 1]


In [28]:
#CODE 
# EVALUATION METHOD
from sklearn.metrics import accuracy_score
accuracy = 100.0 * accuracy_score(Y_test, Y_pred)
print('Accuracy of KNN(with k =2): %.2f %% ' %accuracy)

Accuracy of KNN(with k =2): 96.00 % 


In [29]:
# NHAN XET
# Ở đây có một điều là khi ta tăng số lượng điểm lân cận được xét từ 2 lên 10 thì tỉ lệ chính xác sẽ cao hơn 
# Về mặt phương pháp thì 10 hay 20 thì trong số các điểm lân cận đó , nhãn nào được chọn nhiều hơn sẽ được gán !

In [30]:
# Tối ưu :
# Việc một kết quả là 98% hay 94% trong một tập dữ liệu nhỏ như vậy là chưa tốt 
# Bây giờ chúng ta sẽ nâng cao cách tính toán lên , thay vì trong 10 điểm lân cận xa hay gần đều được bỏ phiếu như nhau 
# bỏ phiếu ( major voting) bây giờ chúng ta sẽ thêm trọng số để có thể tính toán chính xác 


In [31]:
# CODE 
clf2 = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2, weights = 'distance')
clf2.fit(X_train, Y_train)
Y_pred2 = clf2.predict(X_test)
accuracy = 100.0 * accuracy_score(Y_test, Y_pred2)

print("Accuracy of 10NN (1/distance weights):", accuracy)

# Comment 
# Ở đây chungs ta thấy rằng : Sklearn cho phép chúng ta đánh trọng số bằng 2 phương pháp đó là 
# weights = 'distance' có nghĩa là điểm càng gần với điểm test đang xét sẽ được đánh trọng số càng lớn với công thức là 
# với công thứ 1/distance , điểm càng xa thì trọng số của chúng càng thấp 


Accuracy of 10NN (1/distance weights): 98.0


In [ ]:
# Nhận xét : 
# Rõ ràng về mặt lý thuyết việc đánh trọng số là đạt hiệu quả rõ ràng , và trong đa số các lần chạy thì 
# kết quả của thuật toán K-NN với cơ chế uniform là tốt hơn 
# Tuy nhiên vẫn tồn tại trường hợp phân chia dữ liệu test và dữ liệu train cho kết quả rất xấu , kết quả rất tốt 
# ví thế chúng ta phải thử với nhiều cách chia dữ liệu khác nhau , và tính kết quả trung bình 

In [ ]:
# Nhận xét về K-NN
# ƯU ĐIỂM 
# 1 Độ phực tạp của quá trình training =0 ( Có nghĩa là thời gian training bằng 0 mà là lưu trữ dữ liệu trong bộ nhớ)
# Việc dự đoán đơn giản
# NHƯỢC ĐIỂM 
# Lưu toàn bộ dữ liệu dẫn đến hiệu năng của thuật toán 
# Việc tính toàn nằm toàn ở khâu TEST( Thực tế là không học gì ) nếu K được gán giá trị cao sẽ tốn rất nhiều thời gian 

In [ ]:
# Sau khi chạy thuật toán K-NN với dữ liệu http://yann.lecun.com/exdb/mnist/ - lượng dữ liệu lớn hơn rất nhiều 
# Kết quả thu được với 1-NN là 96% khá tốt , thơi gian chạy >700s
# K-NN  bị đánh giá là thuật toán gặp vấn đề với bài toán số chiều dữ liệu lớn , số điểm dữ liệu lớn 
# K-NN bị ảnh hưởng rất lớn bởi nhiễu với các K thấp , giả sử có 1 phần tử chọn Yes , 1 phần tử chọn NO 